//
//  ContactsTests-ContactsMocks.generated.swift
//  Contacts
//
//  Generated by Mockingbird v0.20.0.
//  DO NOT EDIT
//

@testable import Contacts
@testable import Mockingbird
import CoreData
import Foundation
import Swift
import SwiftUI
import Swinject

// No mocks used in 'ContactsTests'. Mockingbird is configured to only generate mocks for types that
// are explicitly initialized in your tests with `mock(SomeType.self)`. For more information, see
// 'Thunk Pruning' in the README.
